---
title: "Personality, Values and Careers-Success of Accountants: Evidence from the Socio-Economic Panel"
author: "Ulf Brüggemann & Jonas Materna"
institute: "TRR 266 Accounting for Transparency"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: "9pt"
output: 
  beamer_presentation: 
    latex_engine: xelatex # pdflatex creates rastered fonts
    slide_level: 3

        
header-includes:
- \usepackage{booktabs} 
- \usepackage{threeparttable}
- \usepackage{graphicx}
- \input{beamer_theme_trr266.sty}
---


```{r setup, include=FALSE, cache=F, message=F, warning=F, results="hide"}
knitr::opts_chunk$set(
  cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE
)
library(tidyverse)
library(kableExtra)
load("../output/results.rda")



```


### Big 5 Personality Slide
``` {r tab_big5, results="asis"}
var_names <- var_names_big5
tab <- reg_big5$table
tab[12] <- paste(
  "\\\\[-1.8ex] &", var_names$label[1], 
  "&", var_names$label[2], 
  "&", var_names$label[3], 
  "&", var_names$label[4],
  "&", var_names$label[5],"\\\\"
)
esc_var_names <- str_replace_all(var_names$var_name, fixed ("_"), "\\_")
reg_names <- tibble(
  var_name = esc_var_names[c(6:8)],
  label = var_names$label[c(6:8)]
)
for (i in seq(15, 21, by = 3)) {
  pos <- (i-12)/3
  tab[i] <- str_replace(
    tab[i], fixed(reg_names$var_name[pos]), reg_names$label[pos]
  )
}
latex_tab <- c(
  "\\begin{center}",
  "\\resizebox*{!}{0.5\\textheight}{",
  "\\begin{tabular}{lccccc}",
  tab[8:33],
  "\\end{tabular}}",
  "\\end{center}"
)
cat(paste(latex_tab, collapse = "\n"))
```



### Climate Slide
``` {r tab_climate, results="asis"}
var_names <- var_names_climate
tab <- reg_climate$table
tab[12] <- paste(
  "\\\\[-1.8ex] &", var_names$label[1], 
  "&", var_names$label[1], 
  "&", var_names$label[1],
  "&", var_names$label[1],
  "\\\\"
)
esc_var_names <- str_replace_all(var_names$var_name, fixed ("_"), "\\_")
reg_names <- tibble(
  var_name = esc_var_names[c(2:7)],
  label = var_names$label[c(2:7)]
)
for (i in seq(15, 30, by = 3)) {
  pos <- (i-12)/3
  tab[i] <- str_replace(
    tab[i], fixed(reg_names$var_name[pos]), reg_names$label[pos]
  )
}
latex_tab <- c(
  "\\begin{center}",
  "\\resizebox*{!}{0.8\\textheight}{",
  "\\begin{tabular}{lccccc}",
  tab[8:42],
  "\\end{tabular}}",
  "\\end{center}"
)
cat(paste(latex_tab, collapse = "\n"))
```


### Crime Slide
``` {r tab_crime, results="asis"}
var_names <- var_names_crime
tab <- reg_crime$table
tab[12] <- paste(
  "\\\\[-1.8ex] &", var_names$label[1], 
  "&", var_names$label[1], 
  "&", var_names$label[1],
  "&", var_names$label[1],
  "\\\\"
)
esc_var_names <- str_replace_all(var_names$var_name, fixed ("_"), "\\_")
reg_names <- tibble(
  var_name = esc_var_names[c(2:7)],
  label = var_names$label[c(2:7)]
)
for (i in seq(15, 30, by = 3)) {
  pos <- (i-12)/3
  tab[i] <- str_replace(
    tab[i], fixed(reg_names$var_name[pos]), reg_names$label[pos]
  )
}
latex_tab <- c(
  "\\begin{center}",
  "\\resizebox*{!}{0.8\\textheight}{",
  "\\begin{tabular}{lccccc}",
  tab[8:42],
  "\\end{tabular}}",
  "\\end{center}"
)
cat(paste(latex_tab, collapse = "\n"))
```



### Leadership
``` {r tab_job_leadership, results="asis"}
var_names <- var_names_leader
tab <- reg_leader$table
tab[12] <- paste(
  "\\\\[-1.8ex] &", var_names$label[1],"&", var_names$label[1],"&", var_names$label[1],
  "\\\\"
)
esc_var_names <- str_replace_all(var_names$var_name, fixed ("_"), "\\_")
reg_names <- tibble(
  var_name = esc_var_names[c(2:11)],
  label = var_names$label[c(2:11)]
)
for (i in seq(15, 39, by = 3)) {
  pos <- (i-12)/3
  tab[i] <- str_replace(
    tab[i], fixed(reg_names$var_name[pos]), reg_names$label[pos]
  )
}
latex_tab <- c(
  "\\begin{center}",
  "\\resizebox*{!}{0.8\\textheight}{",
  "\\begin{tabular}{lccccc}",
  tab[8:51],
  "\\end{tabular}}",
  "\\end{center}"
)
cat(paste(latex_tab, collapse = "\n"))
```



### Leadership Accountants
``` {r tab_job_leadership_acc, results="asis"}
var_names <- var_names_leader_acc
tab <- reg_leader_acc$table
tab[12] <- paste(
  "\\\\[-1.8ex] &", var_names$label[1],
  "\\\\"
)
esc_var_names <- str_replace_all(var_names$var_name, fixed ("_"), "\\_")
reg_names <- tibble(
  var_name = esc_var_names[c(2:11)],
  label = var_names$label[c(2:11)]
)
for (i in seq(14, 36, by = 3)) {
  pos <- (i-11)/3
  tab[i] <- str_replace(
    tab[i], fixed(reg_names$var_name[pos]), reg_names$label[pos]
  )
}
latex_tab <- c(
  "\\begin{center}",
  "\\resizebox*{!}{0.8\\textheight}{",
  "\\begin{tabular}{lccccc}",
  tab[8:50],
  "\\end{tabular}}",
  "\\end{center}"
)
cat(paste(latex_tab, collapse = "\n"))
```



### Leadership Business Professionals
``` {r tab_job_leadership_bus, results="asis"}
var_names <- var_names_leader_bus
tab <- reg_leader_bus$table
tab[12] <- paste(
  "\\\\[-1.8ex] &", var_names$label[1],
  "\\\\"
)
esc_var_names <- str_replace_all(var_names$var_name, fixed ("_"), "\\_")
reg_names <- tibble(
  var_name = esc_var_names[c(2:11)],
  label = var_names$label[c(2:11)]
)
for (i in seq(14, 36, by = 3)) {
  pos <- (i-11)/3
  tab[i] <- str_replace(
    tab[i], fixed(reg_names$var_name[pos]), reg_names$label[pos]
  )
}
latex_tab <- c(
  "\\begin{center}",
  "\\resizebox*{!}{0.8\\textheight}{",
  "\\begin{tabular}{lccccc}",
  tab[8:50],
  "\\end{tabular}}",
  "\\end{center}"
)
cat(paste(latex_tab, collapse = "\n"))
```